### ISSUE TITLE
[Feat] 24시간 이후 투표 종료 구현

### ISSUE THREAD

**Issue by mxinseo** [2024-4LINETHON-PlanPal/2024-4LINETHON-PlanPal-Server#53]
## Issue
24시간 이후 투표 종료 구현

## To-do

- [x] 채널 웹소켓 구현
- [x] 24시간 이후 투표 종료 구현
    - [x] voting -> confirming으로 바뀌는지 확인
    - [x] 과반수 옵션으로 정해지는지 확인
    - [x] 투표 동률인 경우 가장 이른 약속으로 정해지는지
