### ISSUE TITLE
[Feat] 반환 정보 수정

### ISSUE THREAD

**Issue by mxinseo** [2024-4LINETHON-PlanPal/2024-4LINETHON-PlanPal-Server#55]
## Issue
불필요한 반환 정보들 제거/수정

## To-do

- [x] promise_option의 title 제거
- [x] marks 로직 수정
- [x] new_memo_content 없을 때 제거
